### ISSUE TITLE
Null (Error) when doing /ttt leave

### ISSUE THREAD

**Issue by VincentVerdynanta** [caseif/TTT#35]
Whenever I tried to do /ttt leave, it outputs a null (error)
![2015-11-27_18 34 32](https://cloud.githubusercontent.com/assets/2397514/11440520/94f849b8-9535-11e5-9323-35b7b1a173fd.png)

Console:

```
27.11 05:22:07 [Server] INFO ... 15 more
27.11 05:22:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at net.caseif.ttt.command.CommandManager.onCommand(CommandManager.java:122) ~[?:?]
27.11 05:22:07 [Server] INFO at net.caseif.ttt.command.CommandRef.invoke(CommandRef.java:100) ~[?:?]
27.11 05:22:07 [Server] INFO at net.caseif.ttt.command.handler.use.LeaveCommand.handle(LeaveCommand.java:46) ~[?:?]
27.11 05:22:07 [Server] INFO at net.caseif.flint.common.challenger.CommonChallenger.removeFromRound(CommonChallenger.java:95) ~[?:?]
27.11 05:22:07 [Server] INFO at net.caseif.flint.common.round.CommonRound.removeChallenger(CommonRound.java:200) ~[?:?]
27.11 05:22:07 [Server] INFO at net.caseif.flint.steel.round.SteelRound.removeChallenger(SteelRound.java:138) ~[?:?]
27.11 05:22:07 [Server] INFO at net.caseif.flint.common.round.CommonRound.removeChallenger(CommonRound.java:188) ~[?:?]
27.11 05:22:07 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.google.common.collect.BiMap.remove(Ljava/lang/Object;Ljava/lang/Object;)Z
27.11 05:22:07 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
27.11 05:22:07 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
27.11 05:22:07 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
27.11 05:22:07 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot188.jar:git-Spigot-76236cb-62a2169]
27.11 05:22:07 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ttt' in plugin TTT v0.9.0
27.11 05:22:07 [Server] ERROR null
```

**Comment by caseif** [comment]
That's... er... _really_ odd. Does this persist through server restarts? Are you able to replicate it if all plugins except Steel and TTT are disabled?

Edit: If these fixes don't work, it's possible that your Java installation may be corrupted. Do you have the proper access to reinstall it or install Java 8?

**Comment by VincentVerdynanta** [comment]
This doesn't persist through several server restarts

**Comment by caseif** [comment]
Have you been able to replicate it after restarting since the initial incident?

**Comment by VincentVerdynanta** [comment]
Yes I could replicate it, the initial incident keep appearing even though the server had been restarted

**Comment by caseif** [comment]
This seems to be caused by a reference to a method introduced by Java 8. I'm not sure how it slipped by, but I'll try to get a hotfix out tonight to fix this behavior. Alternatively, if you have proper access, upgrading your server to Java 8 will also resolve the error.

**Comment by caseif** [comment]
Fixed via [Steel/`f0525f1`](https://github.com/caseif/Steel/commit/f0525f17e4cbef2133f94f2e0429cea6d679b9f6).

**Comment by VincentVerdynanta** [comment]
Nope, it's not fixed, even though Steel has been updated to v1.1.3

Steel Update:

```
28.11 06:08:02 [Server] INFO Finished updating.
28.11 06:08:02 [Server] INFO Downloading update: 100% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 90% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 90% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 80% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 80% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 70% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 70% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 60% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 60% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 50% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 50% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 40% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 40% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 30% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 30% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 20% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 20% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 10% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 10% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 0% of 218514 bytes.
28.11 06:08:02 [Server] INFO Downloading update: 0% of 218514 bytes.
28.11 06:08:02 [Server] INFO About to download a new update: Steel v1.1.3
```

/ttt leave:

```
28.11 06:09:19 [Server] INFO ... 15 more
28.11 06:09:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at net.caseif.ttt.command.CommandManager.onCommand(CommandManager.java:122) ~[?:?]
28.11 06:09:19 [Server] INFO at net.caseif.ttt.command.CommandRef.invoke(CommandRef.java:100) ~[?:?]
28.11 06:09:19 [Server] INFO at net.caseif.ttt.command.handler.use.LeaveCommand.handle(LeaveCommand.java:46) ~[?:?]
28.11 06:09:19 [Server] INFO at net.caseif.flint.common.challenger.CommonChallenger.removeFromRound(CommonChallenger.java:95) ~[?:?]
28.11 06:09:19 [Server] INFO at net.caseif.flint.common.round.CommonRound.removeChallenger(CommonRound.java:201) ~[?:?]
28.11 06:09:19 [Server] INFO at net.caseif.flint.steel.round.SteelRound.removeChallenger(SteelRound.java:138) ~[?:?]
28.11 06:09:19 [Server] INFO at net.caseif.flint.common.round.CommonRound.removeChallenger(CommonRound.java:188) ~[?:?]
28.11 06:09:19 [Server] INFO Caused by: java.lang.NoSuchMethodError: com.google.common.collect.BiMap.remove(Ljava/lang/Object;Ljava/lang/Object;)Z
28.11 06:09:19 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
28.11 06:09:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557) [Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654) [Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374) [Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:715) [Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
28.11 06:09:19 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
28.11 06:09:19 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:997) [Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1162) [Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:641) ~[Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[Spigot188.jar:git-Spigot-76236cb-62a2169]
28.11 06:09:19 [Server] INFO org.bukkit.command.CommandException: Unhandled exception executing command 'ttt' in plugin TTT v0.9.1
28.11 06:09:19 [Server] ERROR null
```

**Comment by caseif** [comment]
You'll need to restart the server before the update can take effect.

**Comment by ghost** [comment]
@VincentVerdynanta  So is it fixed?
